/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-01-02T22:35:02.857Z")

@Api(value = "findGameByDate", description = "the findGameByDate API")
public interface FindGameByDateApi {

    @ApiOperation(value = "Find game that have been played on the specified dates", nickname = "findGamesByDate", notes = "", response = String.class, tags = {"Games",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = String.class)})
    @RequestMapping(value = "/findGameByDate",
            produces = {"text/plain"},
            method = RequestMethod.GET)
    ResponseEntity<String> findGamesByDate(@NotNull @ApiParam(value = "Date of the game (format: YYYY-MM-DD)", required = true) @Valid @RequestParam(value = "gameDate", required = true) Long gameDate);

}
