/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.10).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-01-02T22:35:02.857Z")

@Api(value = "findResultByPlayerAndGame", description = "the findResultByPlayerAndGame API")
public interface FindResultByPlayerAndGameApi {

    @ApiOperation(value = "Find results for game and/or player", nickname = "findResultByPlayerAndGame", notes = "", response = String.class, tags = {"Results",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "successful operation", response = String.class)})
    @RequestMapping(value = "/findResultByPlayerAndGame",
            produces = {"text/plain"},
            consumes = {"application/x-www-form-urlencoded"},
            method = RequestMethod.GET)
    ResponseEntity<String> findResultByPlayerAndGame(@ApiParam(value = "Game for the result") @RequestParam(value = "gameId", required = false) String gameId, @ApiParam(value = "Player that participate in the game") @RequestParam(value = "playerId", required = false) String playerId);

}
